export { PageNotFound } from './404';
export { About } from './About';
export { Contact } from './Contact';
export { EditProfile } from './EditProfile';
export { Login } from './Login';
export { Menu } from './Menu';
export { OnlineOrder } from './OnlineOrder';
export { SignUp } from './SignUp';
export { UserProfile } from './UserProfile';
